// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7J7LgwxLR4EtAfyNFXD3zT89CboUpCg',
    appId: '1:720042831089:android:36ad92b5c0143e7ec9cd50',
    messagingSenderId: '720042831089',
    projectId: 'shiftmate-8f0e2',
    databaseURL: 'https://shiftmate-8f0e2-default-rtdb.firebaseio.com',
    storageBucket: 'shiftmate-8f0e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGLUViyCHyxcwqxorScJNM_Fb1_VZ9iQY',
    appId: '1:720042831089:ios:72ca034e9aa5cdf1c9cd50',
    messagingSenderId: '720042831089',
    projectId: 'shiftmate-8f0e2',
    databaseURL: 'https://shiftmate-8f0e2-default-rtdb.firebaseio.com',
    storageBucket: 'shiftmate-8f0e2.firebasestorage.app',
    iosBundleId: 'com.shiftmate.shiftMate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQn0mRRnlzCOZV2wrzIkNuax56mQiZ2lc',
    appId: '1:720042831089:web:b10967788d14d54bc9cd50',
    messagingSenderId: '720042831089',
    projectId: 'shiftmate-8f0e2',
    authDomain: 'shiftmate-8f0e2.firebaseapp.com',
    databaseURL: 'https://shiftmate-8f0e2-default-rtdb.firebaseio.com',
    storageBucket: 'shiftmate-8f0e2.firebasestorage.app',
  );

}